web:
  replicas: 2
  image: 'ghcr.io/avazhnov-griddynamics/python-flask-hello'
  # Workaround for Minikube, to not try to pull local images: use `imagePullPolicy: Never`
  imagePullPolicy: IfNotPresent
  tag: v0.9.1
  resources:
    requests:
      memory: 64Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 200m
ingress:
  enabled: true
