web:
  replicas: 2
  image: 'ghcr.io/avazhnov-griddynamics/python-flask-hello'
  tag: v0.2.7
  resources:
    requests:
      memory: 64Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 200m
ingress:
  enabled: true
