---
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-flask-hello-web
  namespace: {{ .Release.Namespace }}
spec:
  defaultBackend:
    service:
      name: python-flask-svc
      port:
        name: flask-http
        # number: 80
  rules:
    - host: '{{ .Values.ingress.host }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-flask-svc
                port:
                  name: flask-http
                  # number: 8080
{{- end -}}
