apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-flask-hello
  name: python-flask-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: flask-http
    port: 80
    # protocol: TCP
    targetPort: flask
  selector:
    app: python-flask-hello
  type: NodePort  # For easy access in Minikube
