name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Login into GitHub container registry with a personal access token
      run: echo '${{ secrets.PERSONAL_ACCESS_TOKEN_CONTAINER_REGISTRY }}' | docker login ghcr.io -u 'avazhnov-griddynamics' --password-stdin

    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build --file Dockerfile_alpine --tag 'ghcr.io/avazhnov-griddynamics/python-flask-hello:alpine' .

    - name: List Docker image(s)
      run: docker images --no-trunc

    - name: Push the Docker image
      run: docker push 'ghcr.io/avazhnov-griddynamics/python-flask-hello:alpine'
