name: Trivy vulnerability scanner

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build --file Dockerfile_alpine --tag "ghcr.io/avazhnov-griddynamics/python-flask-hello:${{ github.sha }}" .

    - name: List Docker image(s)
      run: docker images --no-trunc

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: "ghcr.io/avazhnov-griddynamics/python-flask-hello:${{ github.sha }}"
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
