name: Trivy vulnerability scanner

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
      - "master"

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      security-events: write

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build --file Dockerfile_devuan --tag "ghcr.io/avazhnov-griddynamics/python-flask-hello:${{ github.sha }}" .

    - name: List Docker image(s)
      run: docker images --no-trunc

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: "ghcr.io/avazhnov-griddynamics/python-flask-hello:${{ github.sha }}"
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
